// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd7mp7keds3GNa77C7IH8FgN1BAwp1YLc',
    appId: '1:1084582462207:web:52c2274bd2565a5b5902ca',
    messagingSenderId: '1084582462207',
    projectId: 'sharedtodoapp-ef38f',
    authDomain: 'sharedtodoapp-ef38f.firebaseapp.com',
    databaseURL: 'https://sharedtodoapp-ef38f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sharedtodoapp-ef38f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkUyWZHbW_G08YEfQ61RvlEem8F0j4UUg',
    appId: '1:1084582462207:android:5f7fcbb380bbbae35902ca',
    messagingSenderId: '1084582462207',
    projectId: 'sharedtodoapp-ef38f',
    databaseURL: 'https://sharedtodoapp-ef38f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sharedtodoapp-ef38f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe5b2iVSZYrVTg5EgSeDGPn__mgkFm61g',
    appId: '1:1084582462207:ios:69585adb3d0102965902ca',
    messagingSenderId: '1084582462207',
    projectId: 'sharedtodoapp-ef38f',
    databaseURL: 'https://sharedtodoapp-ef38f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sharedtodoapp-ef38f.firebasestorage.app',
    iosBundleId: 'com.example.listtodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe5b2iVSZYrVTg5EgSeDGPn__mgkFm61g',
    appId: '1:1084582462207:ios:69585adb3d0102965902ca',
    messagingSenderId: '1084582462207',
    projectId: 'sharedtodoapp-ef38f',
    databaseURL: 'https://sharedtodoapp-ef38f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sharedtodoapp-ef38f.firebasestorage.app',
    iosBundleId: 'com.example.listtodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd7mp7keds3GNa77C7IH8FgN1BAwp1YLc',
    appId: '1:1084582462207:web:1d431acb31ea46e25902ca',
    messagingSenderId: '1084582462207',
    projectId: 'sharedtodoapp-ef38f',
    authDomain: 'sharedtodoapp-ef38f.firebaseapp.com',
    databaseURL: 'https://sharedtodoapp-ef38f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sharedtodoapp-ef38f.firebasestorage.app',
  );
}
