import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:share_plus/share_plus.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'package:url_launcher/url_launcher.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const ToDoApp());
}

// Main App
class ToDoApp extends StatelessWidget {
  const ToDoApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Shared To-Do',
      theme: ThemeData(
        colorSchemeSeed: Colors.teal,
        useMaterial3: true,
      ),
      home: const ToDoPage(),
    );
  }
}

// Task model
class Task {
  String id;
  String title;
  String description;
  String location;
  bool done;

  Task({
    required this.id,
    required this.title,
    this.description = '',
    this.location = '',
    this.done = false,
  });

  Map<String, dynamic> toMap() {
    return {
      'title': title,
      'description': description,
      'location': location,
      'done': done,
    };
  }

  factory Task.fromMap(String id, Map<dynamic, dynamic> map) {
    return Task(
      id: id,
      title: map['title'] ?? '',
      description: map['description'] ?? '',
      location: map['location'] ?? '',
      done: map['done'] ?? false,
    );
  }
}

// Main page with tabs
class ToDoPage extends StatefulWidget {
  const ToDoPage({super.key});

  @override
  State<ToDoPage> createState() => _ToDoPageState();
}

class _ToDoPageState extends State<ToDoPage>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;
  final DatabaseReference _tasksRef =
      FirebaseDatabase.instance.ref().child('tasks');

  List<Task> _todoTasks = [];
  List<Task> _doneTasks = [];

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);

    // Listen to tasks in Realtime Database
    _tasksRef.onValue.listen((event) {
      final data = event.snapshot.value as Map<dynamic, dynamic>?;

      List<Task> todos = [];
      List<Task> dones = [];

      if (data != null) {
        data.forEach((key, value) {
          final task = Task.fromMap(key, value);
          if (task.done) {
            dones.add(task);
          } else {
            todos.add(task);
          }
        });
      }

      setState(() {
        _todoTasks = todos;
        _doneTasks = dones;
      });
    });
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  void _moveToDone(Task task) {
    _tasksRef.child(task.id).update({'done': true});
  }

  void _undoDone(Task task) {
    _tasksRef.child(task.id).update({'done': false});
  }

  void _deleteTask(Task task) {
    _tasksRef.child(task.id).remove();
  }

  Future<void> _openAddTaskDialog() async {
    final Task? newTask = await showDialog<Task>(
      context: context,
      builder: (context) => const AddTaskDialog(),
    );
    if (newTask != null) {
      final newRef = _tasksRef.push();
      newTask.id = newRef.key!;
      newRef.set(newTask.toMap());
    }
  }

  Future<void> _openTaskDetail(Task task) async {
    await showDialog(
      context: context,
      builder: (context) => TaskDetailDialog(task: task, ref: _tasksRef),
    );
  }

  void _shareTask(Task task) {
    Share.share(
      'Task: ${task.title}\nDescription: ${task.description}\nLocation: ${task.location}',
    );
  }

  Widget _buildTaskTile(Task task, {required bool isTodo}) {
    return Dismissible(
      key: Key(task.id),
      direction: isTodo
          ? DismissDirection.startToEnd
          : DismissDirection.startToEnd, // swipe → move/undo
      background: Container(
        color: isTodo ? Colors.green : Colors.orange,
        alignment: Alignment.centerLeft,
        padding: const EdgeInsets.symmetric(horizontal: 20),
        child: Icon(
          isTodo ? Icons.check : Icons.undo,
          color: Colors.white,
        ),
      ),
      onDismissed: (_) {
        if (isTodo) {
          _moveToDone(task);
        } else {
          _undoDone(task);
        }
      },
      child: ListTile(
        title: Text(
          task.title,
          softWrap: true,
          style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
        ),
        trailing: Row(
          mainAxisSize: MainAxisSize.min,
          children: isTodo
              ? [
                  if (task.location.isNotEmpty)
                    IconButton(
                      icon: const Icon(Icons.location_on, color: Colors.blue),
                      onPressed: () async {
                        final uri = Uri.parse(task.location);
                        if (await canLaunchUrl(uri)) {
                          await launchUrl(uri);
                        }
                      },
                    ),
                  IconButton(
                    icon: const Icon(Icons.check),
                    onPressed: () => _moveToDone(task),
                  ),
                ]
              : [
                  IconButton(
                    icon: const Icon(Icons.undo, color: Colors.orange),
                    onPressed: () => _undoDone(task),
                  ),
                  IconButton(
                    icon: const Icon(Icons.delete),
                    onPressed: () => _deleteTask(task),
                  ),
                ],
        ),
        onTap: () => _openTaskDetail(task),
        onLongPress: () => _shareTask(task),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('My To-Do List'),
        bottom: TabBar(
          controller: _tabController,
          tabs: [
            Tab(text: 'To-Do (${_todoTasks.length})'),
            Tab(text: 'Done (${_doneTasks.length})'),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          ListView(
            children:
                _todoTasks.map((task) => _buildTaskTile(task, isTodo: true)).toList(),
          ),
          ListView(
            children:
                _doneTasks.map((task) => _buildTaskTile(task, isTodo: false)).toList(),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _openAddTaskDialog,
        child: const Icon(Icons.add),
      ),
    );
  }
}

// Dialog to add a new task
class AddTaskDialog extends StatefulWidget {
  const AddTaskDialog({super.key});

  @override
  State<AddTaskDialog> createState() => _AddTaskDialogState();
}

class _AddTaskDialogState extends State<AddTaskDialog> {
  final TextEditingController _titleController = TextEditingController();
  final TextEditingController _descController = TextEditingController();
  final TextEditingController _locController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Add New Task'),
      content: SingleChildScrollView(
        child: Column(
          children: [
            TextField(
              controller: _titleController,
              decoration: const InputDecoration(labelText: 'Title'),
              maxLines: null,
            ),
            TextField(
              controller: _descController,
              decoration: const InputDecoration(labelText: 'Description'),
              maxLines: null,
            ),
            TextField(
              controller: _locController,
              decoration: const InputDecoration(labelText: 'Location (URL)'),
            ),
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: const Text('Cancel'),
        ),
        ElevatedButton(
          onPressed: () {
            if (_titleController.text.trim().isEmpty) return;
            final task = Task(
              id: '',
              title: _titleController.text.trim(),
              description: _descController.text.trim(),
              location: _locController.text.trim(),
            );
            Navigator.pop(context, task);
          },
          child: const Text('Add'),
        ),
      ],
    );
  }
}

// Dialog to view/edit task details
class TaskDetailDialog extends StatefulWidget {
  final Task task;
  final DatabaseReference ref;
  const TaskDetailDialog({super.key, required this.task, required this.ref});

  @override
  State<TaskDetailDialog> createState() => _TaskDetailDialogState();
}

class _TaskDetailDialogState extends State<TaskDetailDialog> {
  late TextEditingController _titleController;
  late TextEditingController _descController;
  late TextEditingController _locController;

  @override
  void initState() {
    super.initState();
    _titleController = TextEditingController(text: widget.task.title);
    _descController = TextEditingController(text: widget.task.description);
    _locController = TextEditingController(text: widget.task.location);
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descController.dispose();
    _locController.dispose();
    super.dispose();
  }

  Future<void> _launchLocation() async {
    final url = _locController.text.trim();
    if (url.isEmpty) return;
    final uri = Uri.parse(url);
    if (await canLaunchUrl(uri)) {
      await launchUrl(uri);
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Task Details'),
      content: SingleChildScrollView(
        child: Column(
          children: [
            TextField(
              controller: _titleController,
              decoration: const InputDecoration(labelText: 'Title'),
              maxLines: null,
            ),
            TextField(
              controller: _descController,
              decoration: const InputDecoration(labelText: 'Description'),
              maxLines: null,
            ),
            Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _locController,
                    decoration:
                        const InputDecoration(labelText: 'Location (URL)'),
                  ),
                ),
                if (_locController.text.trim().isNotEmpty)
                  IconButton(
                    icon: const Icon(Icons.location_on),
                    onPressed: _launchLocation,
                  ),
              ],
            ),
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: const Text('Cancel'),
        ),
        ElevatedButton(
          onPressed: () {
            widget.ref.child(widget.task.id).update({
              'title': _titleController.text.trim(),
              'description': _descController.text.trim(),
              'location': _locController.text.trim(),
            });
            Navigator.pop(context);
          },
          child: const Text('Save'),
        ),
      ],
    );
  }
}
